name: CI (React + Go)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  react:
    name: Frontend (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Lint
        run: |
          if npm run | grep -q "lint"; then npm run lint; else echo "no lint script"; fi
      - name: Build
        run: |
          if npm run | grep -q "build"; then npm run build; else echo "no build script"; fi
      - name: Test
        run: |
          if npm run | grep -q "test"; then
            npm test -- --run
          else
            echo "no tests"
          fi

  go:
    name: Backend (Go)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Build
        run: go build ./...
      - name: Vet & fmt check
        run: |
          go vet ./...
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files not formatted:"
            gofmt -l .
            exit 1
          fi
      - name: Test
        run: go test ./... -race -coverprofile=coverage.out -v
  status:
    name: Aggregate status
    runs-on: ubuntu-latest
    needs: [react, go]
    steps:
      - run: echo "All good ✅"
